SELECT A.USER_ID
FROM (
    SELECT REVIEWER_ID AS USER_ID, COUNT(REVIEWER_ID) AS COUNT
    FROM PLACE_REVIEWS
    GROUP BY REVIEWER_ID
    ORDER BY COUNT(REVIEWER_ID) DESC
) A
WHERE COUNT = 2
ORDER BY USER_ID