SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM 
    (
    SELECT *
    FROM ANIMAL_INS A 
    WHERE SEX_UPON_INTAKE LIKE "%Intact%"
    ) SQ1, ANIMAL_OUTS B
WHERE SQ1.ANIMAL_ID = B.ANIMAL_ID
AND B.SEX_UPON_OUTCOME NOT LIKE "%Intact%"

-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE "%Intact%" AND B.SEX_UPON_OUTCOME NOT LIKE "%Intact%"
ORDER BY A.ANIMAL_ID